apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
          - name: eureka-server
            image: nttdatabootcampacr.azurecr.io/eureka-server:1.0
            imagePullPolicy: Always
            ports:
              - containerPort: 8761
      imagePullSecrets:
        - name: bootcampsecret